name = "claudecode.link"
main = "src/index.ts"
compatibility_date = "2025-10-02"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "claude-sessions"
database_id = "b716eb9d-8473-4151-ac73-f1bfce4c2eaa"
